openapi: 3.2.0
info:
  title: Fortanix DSM REST Marketplace API
  description: This is a set of REST APIs for accessing the Fortanix Data Security Manager.
  termsOfService: https://fortanix.com/legal/agreements-and-standard-terms
  contact:
    name: Fortanix Support
    url: https://support.fortanix.com/
    email: support@fortanix.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0-20260710
servers:
- url: '{dsmEndpoint}'
  description: DSM Endpoint
  variables:
    dsmEndpoint:
      default: https://amer.smartkey.io
      description: Type your DSM server URL here (include https://)
tags:
- name: Marketplace
paths:
  /sys/v1/marketplace:
    get:
      operationId: GetMarketplace
      tags:
      - Marketplace
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Gets all the plugins from the input url
      description: Gets all the plugins from the input url.
      parameters:
      - $ref: '#/components/parameters/GetMarketplaceParams'
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarketplacePlugin'
components:
  parameters:
    GetMarketplaceParams:
      in: query
      name: GetMarketplaceParams
      schema:
        $ref: '#/components/schemas/GetMarketplaceParams'
      explode: true
  schemas:
    MarketplacePlugin:
      allOf:
      - type: object
        properties:
          name:
            type: string
          versions:
            type: object
            additionalProperties:
              type:
              - string
              - 'null'
        required:
        - name
        - versions
    GetMarketplaceParams:
      allOf:
      - type: object
        properties:
          repo_url:
            type: string
        required:
        - repo_url
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Please enter your token prefixed with 'Basic ' (e.g., 'Basic your_token_here')
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
