openapi: 3.2.0
info:
  title: Fortanix DSM REST Marketplace API
  description: "This is a set of REST APIs for accessing the Fortanix Data Security Manager. This includes APIs for managing accounts, and for performing cryptographic and key management operations. \n\n **Note:** \n- All binary input should be base64-encoded. These fields are marked with `format: byte`. \n- For forward compatibility, any API client is expected to ignore any fields in the response not explicitly mentioned in the documentation. We reserve the right to add new fields at any time to provide new functionality without affecting existing API clients. \n- PATCH requests accept a JSON value describing a partial update to the specified resource. All top-level fields in the PATCH request are optional. If an optional field is omitted, the existing value of that field is preserved. In general, for nested JSON objects, the request must provide the complete object value rather than a partial update."
  termsOfService: https://fortanix.com/legal/agreements-and-standard-terms
  contact:
    name: Fortanix Support
    url: https://support.fortanix.com/
    email: support@fortanix.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0-20260710
servers:
- url: '{dsmEndpoint}'
  description: DSM Endpoint
  variables:
    dsmEndpoint:
      default: https://amer.smartkey.io
      description: Type your DSM server URL here (include https://)
tags:
- name: Marketplace
paths:
  /sys/v1/marketplace:
    get:
      operationId: GetMarketplace
      tags:
      - Marketplace
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Gets all the plugins from the input url.
      description: Gets all the plugins from the input url.
      parameters:
      - $ref: '#/components/parameters/GetMarketplaceParams'
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarketplacePlugin'
components:
  schemas:
    GetMarketplaceParams:
      allOf:
      - type: object
        properties:
          repo_url:
            type: string
        required:
        - repo_url
    MarketplacePlugin:
      allOf:
      - type: object
        properties:
          name:
            type: string
          versions:
            type: object
            additionalProperties:
              type:
              - string
              - 'null'
        required:
        - name
        - versions
  parameters:
    GetMarketplaceParams:
      in: query
      name: GetMarketplaceParams
      schema:
        $ref: '#/components/schemas/GetMarketplaceParams'
      explode: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Please enter your token prefixed with 'Basic ' (e.g., 'Basic your_token_here')
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
