openapi: 3.2.0
info:
  title: Fortanix DSM REST Version API
  description: This is a set of REST APIs for accessing the Fortanix Data Security Manager.
  termsOfService: https://fortanix.com/legal/agreements-and-standard-terms
  contact:
    name: Fortanix Support
    url: https://support.fortanix.com/
    email: support@fortanix.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0-20260710
servers:
- url: '{dsmEndpoint}'
  description: DSM Endpoint
  variables:
    dsmEndpoint:
      default: https://amer.smartkey.io
      description: Type your DSM server URL here (include https://)
tags:
- name: Version
paths:
  /sys/v1/version:
    get:
      operationId: Version
      tags:
      - Version
      summary: Returns information about the DSM server version and the client API version…
      description: 'Returns information about the DSM server version and the client

        API version that it supports.'
      parameters:
      - $ref: '#/components/parameters/VersionParams'
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
components:
  schemas:
    VersionResponse:
      allOf:
      - type: object
        description: Information about the service version.
        properties:
          version:
            type: string
            description: Server version. This is encoded as "major.minor.build".
          api_version:
            type: string
            description: The API version implemented by the server.
          server_mode:
            $ref: '#/components/schemas/ServerMode'
          fips_level:
            type:
            - integer
            - 'null'
            minimum: 0
            maximum: 255
            description: 'FIPS level at which the service in running. If this field is absent, then the service is

              not running in FIPS compliant mode.'
          plugins_digest:
            type: string
            format: byte
            description: 'An opaque digest of all current plugins.


              Only present when the server is running in FIPS mode.'
        required:
        - version
        - api_version
        - server_mode
    ServerMode:
      description: Server execution mode.
      type: string
      enum:
      - Software
      - Sgx
    VersionParams:
      allOf:
      - type: object
        properties:
          detailed_fips_info:
            type: boolean
            description: 'Include FIPS-relevant info in the response. Currently that is `plugins_digest`.


              Only applicable to FIPS builds.'
  parameters:
    VersionParams:
      in: query
      name: VersionParams
      schema:
        $ref: '#/components/schemas/VersionParams'
      explode: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Please enter your token prefixed with 'Basic ' (e.g., 'Basic your_token_here')
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
