openapi: 3.2.0
info:
  title: Fortanix DSM REST External Roles API
  description: This is a set of REST APIs for accessing the Fortanix Data Security Manager.
  termsOfService: https://fortanix.com/legal/agreements-and-standard-terms
  contact:
    name: Fortanix Support
    url: https://support.fortanix.com/
    email: support@fortanix.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0-20260710
servers:
- url: '{dsmEndpoint}'
  description: DSM Endpoint
  variables:
    dsmEndpoint:
      default: https://amer.smartkey.io
      description: Type your DSM server URL here (include https://)
tags:
- name: External Roles
paths:
  /sys/v1/external_roles:
    post:
      operationId: CreateExternalRole
      tags:
      - External Roles
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Create a new external role
      description: Create a new external role.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalRoleRequest'
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalRole'
    get:
      operationId: ListExternalRoles
      tags:
      - External Roles
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Get all external roles
      description: Get all external roles.
      parameters:
      - $ref: '#/components/parameters/ListExternalRolesParams'
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalRole'
  /sys/v1/external_roles/{external_role_id}:
    delete:
      operationId: DeleteExternalRole
      tags:
      - External Roles
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Delete an external role
      description: Delete an external role.
      parameters:
      - name: external_role_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '204':
          description: Nothing is returned on success
    get:
      operationId: GetExternalRole
      tags:
      - External Roles
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Lookup a particular external role by its ID
      description: Lookup a particular external role by its ID.
      parameters:
      - name: external_role_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalRole'
    patch:
      operationId: UpdateExternalRole
      tags:
      - External Roles
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Update an external role
      description: Update an external role.
      parameters:
      - name: external_role_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalRoleRequest'
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalRole'
  /sys/v1/external_roles/{external_role_id}/sync:
    post:
      operationId: SyncExternalRole
      tags:
      - External Roles
      security:
      - bearerToken: []
      - apiKeyAuth: []
      summary: Synchronize information about the external role by retrieving it from external…
      description: Synchronize information about the external role by retrieving it from external source.
      parameters:
      - name: external_role_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        2XX:
          description: Success result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalRole'
components:
  schemas:
    UserGroupRole:
      description: User's role(s) in a group.
      allOf:
      - type: array
        uniqueItems: true
        items:
          $ref: '#/components/schemas/LegacyUserGroupRoleOrRoleId'
    ExternalRoleMapping:
      allOf:
      - type: object
        properties:
          users:
            $ref: '#/components/schemas/UserGroupRole'
          apps:
            type:
            - array
            - 'null'
            items:
              $ref: '#/components/schemas/AppPermissions'
    ExternalRoleKind:
      description: Type of an external role.
      type: string
      enum:
      - ldap-group
    LegacyUserGroupRoleOrRoleId:
      description: Legacy user group role name or custom role id
      oneOf:
      - $ref: '#/components/schemas/LegacyUserGroupRole'
      - type: string
        format: uuid
    ListExternalRolesParams:
      allOf:
      - type: object
        properties:
          group_id:
            type: string
            format: uuid
    ExternalRole:
      allOf:
      - type: object
        properties:
          external_role_id:
            type: string
            format: uuid
          groups:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/ExternalRoleMapping'
          kind:
            $ref: '#/components/schemas/ExternalRoleKind'
          last_synced:
            type: string
            pattern: ^\d{4}\d{2}\d{2}T\d{2}\d{2}\d{2}Z$
            example: 20170509T070912Z
          name:
            type: string
          source_id:
            type: string
            format: uuid
          acct_id:
            type: string
            format: uuid
        required:
        - external_role_id
        - groups
        - kind
        - last_synced
        - name
        - source_id
        - acct_id
    AppPermissions:
      description: "Operations allowed to be performed by an app.\n\n\n\n          SIGN:\n\n\n          VERIFY:\n\n\n          ENCRYPT:\n\n\n          DECRYPT:\n\n\n          WRAPKEY:\n\n\n          UNWRAPKEY:\n\n\n          DERIVEKEY:\n\n\n          MACGENERATE:\n\n\n          MACVERIFY:\n\n\n          EXPORT:\n\n\n          MANAGE:\n\n\n          AGREEKEY:\n\n\n          MASKDECRYPT:\n\n\n          AUDIT:\n\n\n          TRANSFORM:\n\n\n          CREATE_SOBJECTS:\n\n\n          COPY_SOBJECTS:\n\n\n          ROTATE_SOBJECTS:\n\n\n          ACTIVATE_SOBJECTS:\n\n\n          REVOKE_SOBJECTS:\n\n\n          REVERT_SOBJECTS:\n\n\n          MOVE_SOBJECTS:\n\n\n          UPDATE_SOBJECTS_PROFILE:\n\n\n          UPDATE_SOBJECTS_ENABLED_STATE:\n\n\n          UPDATE_SOBJECT_POLICIES:\n\n\n          UPDATE_KEY_OPS:\n\n\n          DELETE_KEY_MATERIAL:\n\n\n          DELETE_SOBJECTS:\n\n\n          DESTROY_SOBJECTS:\n\n\n          RESTORE_EXTERNAL_SOBJECTS:\n\n\n          CALCULATE_DIGEST:\n\n\n          ENCAPSULATE:\n\n\n          DECAPSULATE:\n\n"
      type: string
      enum:
      - SIGN
      - VERIFY
      - ENCRYPT
      - DECRYPT
      - WRAPKEY
      - UNWRAPKEY
      - DERIVEKEY
      - MACGENERATE
      - MACVERIFY
      - EXPORT
      - MANAGE
      - AGREEKEY
      - MASKDECRYPT
      - AUDIT
      - TRANSFORM
      - CREATE_SOBJECTS
      - COPY_SOBJECTS
      - ROTATE_SOBJECTS
      - ACTIVATE_SOBJECTS
      - REVOKE_SOBJECTS
      - REVERT_SOBJECTS
      - MOVE_SOBJECTS
      - UPDATE_SOBJECTS_PROFILE
      - UPDATE_SOBJECTS_ENABLED_STATE
      - UPDATE_SOBJECT_POLICIES
      - UPDATE_KEY_OPS
      - DELETE_KEY_MATERIAL
      - DELETE_SOBJECTS
      - DESTROY_SOBJECTS
      - RESTORE_EXTERNAL_SOBJECTS
      - CALCULATE_DIGEST
      - ENCAPSULATE
      - DECAPSULATE
    LegacyUserGroupRole:
      description: Legacy user group role
      type: string
      enum:
      - GROUPAUDITOR
      - GROUPADMINISTRATOR
    ExternalRoleRequest:
      allOf:
      - type: object
        properties:
          add_groups:
            type:
            - object
            - 'null'
            additionalProperties:
              $ref: '#/components/schemas/ExternalRoleMapping'
          del_groups:
            type:
            - array
            - 'null'
            uniqueItems: true
            items:
              type: string
              format: uuid
          kind:
            $ref: '#/components/schemas/ExternalRoleKind'
          mod_groups:
            type:
            - object
            - 'null'
            additionalProperties:
              $ref: '#/components/schemas/ExternalRoleMapping'
          name:
            type:
            - string
            - 'null'
          source_id:
            type:
            - string
            - 'null'
            format: uuid
  parameters:
    ListExternalRolesParams:
      in: query
      name: ListExternalRolesParams
      schema:
        $ref: '#/components/schemas/ListExternalRolesParams'
      explode: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Please enter your token prefixed with 'Basic ' (e.g., 'Basic your_token_here')
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
